import { Link, useNavigate } from "react-router-dom";
import { useState } from "react";
import { Lock, CheckCircle2 } from "lucide-react";
import { useCart } from "../context/CartContext";
import { useAuth } from "../context/AuthContext";

export default function Checkout(){
 const {cart,total,clearCart}=useCart(); const {user}=useAuth(); const nav=useNavigate(); const [done,setDone]=useState(false);
 const submit=e=>{e.preventDefault();setDone(true);clearCart();setTimeout(()=>nav("/"),1800)};
 if(!cart.length&&!done)return <section className="mx-auto max-w-4xl px-4 py-24 text-center"><h1 className="font-display text-5xl">Nothing to checkout.</h1><Link to="/shop" className="mt-6 inline-flex rounded-full bg-elora-navy px-6 py-3 text-sm font-bold text-white">Shop now</Link></section>;
 if(done)return <section className="mx-auto max-w-2xl px-4 py-28 text-center"><CheckCircle2 className="mx-auto h-16 w-16 text-green-500"/><h1 className="mt-5 font-display text-5xl">Order placed.</h1><p className="mt-3 text-slate-500">Thank you for choosing Elora. We'll take it from here.</p></section>;
 return <section className="mx-auto max-w-6xl px-4 py-12 sm:px-6 lg:px-8 lg:py-16"><p className="text-xs font-bold uppercase tracking-[.2em] text-slate-400">Almost yours</p><h1 className="mt-2 font-display text-5xl">Checkout</h1><div className="mt-10 grid gap-8 lg:grid-cols-[1fr_340px]"><form onSubmit={submit} className="space-y-4 rounded-[2rem] bg-white p-6 sm:p-8 dark:bg-white/[.04]"><h2 className="font-display text-2xl">Delivery details</h2><input required defaultValue={user?.name||""} placeholder="Full name" className="mt-4 w-full rounded-2xl border border-slate-200 bg-transparent px-4 py-3.5 outline-none dark:border-white/10"/><input required type="email" defaultValue={user?.email||""} placeholder="Email" className="w-full rounded-2xl border border-slate-200 bg-transparent px-4 py-3.5 outline-none dark:border-white/10"/><input required placeholder="Address" className="w-full rounded-2xl border border-slate-200 bg-transparent px-4 py-3.5 outline-none dark:border-white/10"/><div className="grid gap-4 sm:grid-cols-2"><input required placeholder="City" className="w-full rounded-2xl border border-slate-200 bg-transparent px-4 py-3.5 outline-none dark:border-white/10"/><input required placeholder="Phone number" className="w-full rounded-2xl border border-slate-200 bg-transparent px-4 py-3.5 outline-none dark:border-white/10"/></div><button className="mt-4 flex w-full items-center justify-center gap-2 rounded-full bg-elora-navy py-4 text-sm font-bold text-white"><Lock size={15}/> Place order</button></form><aside className="h-fit rounded-[2rem] bg-elora-blue/60 p-7"><h2 className="font-display text-2xl">Your order</h2>{cart.slice(0,4).map(x=><div key={x.id} className="mt-4 flex justify-between gap-3 text-sm"><span className="line-clamp-1">{x.title} × {x.qty}</span><b>${(x.price*x.qty).toFixed(2)}</b></div>)}<div className="mt-6 border-t border-elora-navy/10 pt-5 flex justify-between text-lg"><span>Total</span><b>${total.toFixed(2)}</b></div></aside></div></section>
}
