import { useState } from "react";
import { Eye, EyeOff, ArrowRight } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";

export default function Login(){
 const [show,setShow]=useState(false);const [form,setForm]=useState({email:"",password:""});const {login}=useAuth();const nav=useNavigate();
 const submit=e=>{e.preventDefault();login(form);nav("/")};
 return <AuthLayout eyebrow="Welcome back" title="Come on in." text="Your favorites, your bag, your Elora world — all in one place."><form onSubmit={submit} className="space-y-4"><Field label="Email"><input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="you@example.com" className="input"/></Field><Field label="Password"><div className="relative"><input required type={show?"text":"password"} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="••••••••" className="input pr-12"/><button type="button" onClick={()=>setShow(!show)} className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400">{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></Field><div className="flex justify-between text-xs text-slate-500"><label className="flex gap-2"><input type="checkbox"/> Remember me</label><button type="button" className="font-semibold">Forgot password?</button></div><button className="flex w-full items-center justify-center gap-2 rounded-full bg-elora-navy py-4 font-bold text-white">Login <ArrowRight size={17}/></button></form><p className="mt-6 text-center text-sm text-slate-500">New to Elora? <Link to="/register" className="font-bold dark:text-white">Create an account</Link></p></AuthLayout>
}
function Field({label,children}){return <label className="block text-sm font-semibold">{label}{children}</label>}
function AuthLayout({eyebrow,title,text,children}){return <section className="mx-auto grid min-h-[calc(100vh-150px)] max-w-6xl items-center gap-8 px-4 py-10 sm:px-6 lg:grid-cols-2 lg:px-8"><div className="hidden min-h-[590px] rounded-[2rem] bg-elora-blue p-12 lg:flex lg:flex-col lg:justify-end"><p className="text-xs font-bold uppercase tracking-[.2em] text-elora-navy/60">Elora</p><h2 className="mt-3 max-w-md font-display text-6xl text-elora-navy">Everything she loves, in one place.</h2></div><div className="mx-auto w-full max-w-md"><p className="text-xs font-bold uppercase tracking-[.2em] text-slate-400">{eyebrow}</p><h1 className="mt-2 font-display text-5xl">{title}</h1><p className="mb-8 mt-3 text-sm leading-6 text-slate-500">{text}</p>{children}</div></section>}
