import { useState } from "react";
import { Eye, EyeOff, ArrowRight } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";

export default function Register(){
 const [show,setShow]=useState(false);const [error,setError]=useState("");const [form,setForm]=useState({name:"",email:"",password:"",confirm:""});const {register}=useAuth();const nav=useNavigate();
 const submit=e=>{e.preventDefault();if(form.password!==form.confirm){setError("Passwords do not match.");return}if(form.password.length<6){setError("Password must be at least 6 characters.");return}register(form);nav("/")};
 const input="input";
 return <section className="mx-auto grid min-h-[calc(100vh-150px)] max-w-6xl items-center gap-8 px-4 py-10 sm:px-6 lg:grid-cols-2 lg:px-8"><div className="mx-auto w-full max-w-md lg:order-1"><p className="text-xs font-bold uppercase tracking-[.2em] text-slate-400">Join Elora</p><h1 className="mt-2 font-display text-5xl">Make it yours.</h1><p className="mb-8 mt-3 text-sm text-slate-500">Create your account and keep every favorite little thing close.</p><form onSubmit={submit} className="space-y-4"><label className="block text-sm font-semibold">Full name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className={input}/></label><label className="block text-sm font-semibold">Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className={input}/></label><label className="block text-sm font-semibold">Password<div className="relative"><input required minLength={6} type={show?"text":"password"} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} className={`${input} pr-12`}/><button type="button" onClick={()=>setShow(!show)} className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400">{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label><label className="block text-sm font-semibold">Confirm password<input required type="password" value={form.confirm} onChange={e=>setForm({...form,confirm:e.target.value})} className={input}/></label>{error&&<p className="text-xs font-semibold text-red-500">{error}</p>}<label className="flex gap-2 text-xs text-slate-500"><input required type="checkbox"/> I agree to the Terms & Conditions.</label><button className="flex w-full items-center justify-center gap-2 rounded-full bg-elora-navy py-4 font-bold text-white">Create Account <ArrowRight size={17}/></button></form><p className="mt-6 text-center text-sm text-slate-500">Already have an account? <Link to="/login" className="font-bold dark:text-white">Login</Link></p></div><div className="hidden min-h-[590px] rounded-[2rem] bg-elora-blush p-12 lg:order-2 lg:flex lg:flex-col lg:justify-end"><p className="text-xs font-bold uppercase tracking-[.2em] text-elora-navy/60">For her</p><h2 className="mt-3 max-w-md font-display text-6xl text-elora-navy">A little something for every mood.</h2></div></section>
}
